version: '3'

services:
  db:
    image: mysql:8.0.17
    ports:
      - "3306:3306"
      - "3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: monsters_development
      MYSQL_USER: rails
      MYSQL_PASSWORD: 

  web:
    build: .
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -e development -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db_data:

