# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
MoveType.find_or_create_by(name: 'ground')
MoveType.find_or_create_by(name: 'water')
MoveType.find_or_create_by(name: 'air')
MoveType.find_or_create_by(name: 'tunneling')

Location.find_or_create_by(name: 'eye')
Location.find_or_create_by(name: 'skull')
Location.find_or_create_by(name: 'face')
Location.find_or_create_by(name: 'right leg')
Location.find_or_create_by(name: 'right arm')
Location.find_or_create_by(name: 'torso')
Location.find_or_create_by(name: 'groin/abdomen')
Location.find_or_create_by(name: 'left arm')
Location.find_or_create_by(name: 'left leg')
Location.find_or_create_by(name: 'right hand')
Location.find_or_create_by(name: 'left hand')
Location.find_or_create_by(name: 'right foot')
Location.find_or_create_by(name: 'left foot')
Location.find_or_create_by(name: 'neck')
Location.find_or_create_by(name: 'vitals')

MonsterClass.find_or_create_by(name: 'Animal')
MonsterClass.find_or_create_by(name: 'Animal, Dire')
MonsterClass.find_or_create_by(name: 'Animal, Giant')
MonsterClass.find_or_create_by(name: 'Construct')
MonsterClass.find_or_create_by(name: 'Demon')
MonsterClass.find_or_create_by(name: 'Elder Thing')
MonsterClass.find_or_create_by(name: 'Elemental')
MonsterClass.find_or_create_by(name: 'Faerie')
MonsterClass.find_or_create_by(name: 'Hybrid')
MonsterClass.find_or_create_by(name: 'Mundane')
MonsterClass.find_or_create_by(name: 'Plant')
MonsterClass.find_or_create_by(name: 'Slime')
MonsterClass.find_or_create_by(name: 'Undead')


st =Characteristic.find_or_create_by(name: 'ST', sequence_number: 1, base_value: 10 )
dx = Characteristic.find_or_create_by(name: 'DX', sequence_number: 2, base_value: 10 )
iq = Characteristic.find_or_create_by(name: 'IQ', sequence_number: 3, base_value: 10 )
ht = Characteristic.find_or_create_by(name: 'HT', sequence_number: 4, base_value: 10 )
Characteristic.find_or_create_by(name: 'HP', sequence_number: 5, base_value: 10 )
will = Characteristic.find_or_create_by(name: 'Will', sequence_number: 6, base_value: 10 )
per = Characteristic.find_or_create_by(name: 'Per', sequence_number: 7, base_value: 10 )
Characteristic.find_or_create_by(name: 'Fatigue', sequence_number: 8, base_value: 10 )
Characteristic.find_or_create_by(name: 'Speed', sequence_number: 9, step_size: 0.25, base_value: 5.0 )
Characteristic.find_or_create_by(name: 'SM', sequence_number: 10, base_value: 0 )


MasterSkill.find_or_create_by(name: 'Acrobatics', characteristic: dx )
MasterSkill.find_or_create_by(name: 'Acting', characteristic: iq )
MasterSkill.find_or_create_by(name: 'Alchemy', characteristic: iq, requires_tech_level: true )
MasterSkill.find_or_create_by(name: 'Animal Handling', characteristic: iq, requires_specialization: true )
MasterSkill.find_or_create_by(name: 'Architecture', characteristic: iq, requires_tech_level: true )
MasterSkill.find_or_create_by(name: 'Area Knowledge', characteristic: iq, requires_specialization: true )
MasterSkill.find_or_create_by(name: 'Armoury', characteristic: iq, requires_specialization: true )
MasterSkill.find_or_create_by(name: 'Axe/Mace', characteristic: dx )
MasterSkill.find_or_create_by(name: 'Blowpipe', characteristic: dx )
MasterSkill.find_or_create_by(name: 'Boating', characteristic: dx, requires_specialization: true )
MasterSkill.find_or_create_by(name: 'Body Language', characteristic: per )
MasterSkill.find_or_create_by(name: 'Body Sense', characteristic: dx )
MasterSkill.find_or_create_by(name: 'Bolas', characteristic: dx )
MasterSkill.find_or_create_by(name: 'Bow', characteristic: dx )
MasterSkill.find_or_create_by(name: 'Boxing', characteristic: dx )
MasterSkill.find_or_create_by(name: 'Brawling', characteristic: dx )
MasterSkill.find_or_create_by(name: 'Broadsword', characteristic: dx )
MasterSkill.find_or_create_by(name: 'Camouflage', characteristic: iq )
MasterSkill.find_or_create_by(name: 'Carousing', characteristic: ht )
MasterSkill.find_or_create_by(name: 'Cartography', characteristic: iq )
MasterSkill.find_or_create_by(name: 'Climbing', characteristic: dx )
MasterSkill.find_or_create_by(name: 'Cloak', characteristic: dx )
MasterSkill.find_or_create_by(name: 'Counterfeiting', characteristic: iq, requires_tech_level: true )
MasterSkill.find_or_create_by(name: 'Crossbow', characteristic: dx )
MasterSkill.find_or_create_by(name: 'Current Affairs', characteristic: iq, requires_specialization: true )
MasterSkill.find_or_create_by(name: 'Dancing', characteristic: dx )
MasterSkill.find_or_create_by(name: 'Detect Lies', characteristic: per )
MasterSkill.find_or_create_by(name: 'Diagnosis', characteristic: iq, requires_tech_level: true )
MasterSkill.find_or_create_by(name: 'Diplomacy', characteristic: iq )
MasterSkill.find_or_create_by(name: 'Disguise', characteristic: iq, requires_tech_level: true )
MasterSkill.find_or_create_by(name: 'Engineer', characteristic: iq, requires_specialization: true, requires_tech_level: true )
MasterSkill.find_or_create_by(name: 'Erotic Art', characteristic: dx )
MasterSkill.find_or_create_by(name: 'Escape', characteristic: dx )
MasterSkill.find_or_create_by(name: 'Falconry', characteristic: iq )
MasterSkill.find_or_create_by(name: 'Fast-Draw', characteristic: dx, requires_specialization: true )
MasterSkill.find_or_create_by(name: 'Fast-Talk', characteristic: iq )
MasterSkill.find_or_create_by(name: 'Filch', characteristic: dx )
MasterSkill.find_or_create_by(name: 'First Aid', characteristic: iq, requires_tech_level: true )
MasterSkill.find_or_create_by(name: 'Fishing', characteristic: per )
MasterSkill.find_or_create_by(name: 'Flail', characteristic: dx )
MasterSkill.find_or_create_by(name: 'Forced Entry', characteristic: dx )
MasterSkill.find_or_create_by(name: 'Forgery', characteristic: iq, requires_tech_level: true )
MasterSkill.find_or_create_by(name: 'Gambling', characteristic: iq )
MasterSkill.find_or_create_by(name: 'Games', characteristic: iq, requires_specialization: true )
MasterSkill.find_or_create_by(name: 'Garrote', characteristic: dx )
MasterSkill.find_or_create_by(name: 'Gesture', characteristic: iq )
MasterSkill.find_or_create_by(name: 'Hazardous Materials', characteristic: iq, requires_specialization: true )
MasterSkill.find_or_create_by(name: 'Heraldry', characteristic: iq )
MasterSkill.find_or_create_by(name: 'Hidden Lore', characteristic: iq, requires_specialization: true )
MasterSkill.find_or_create_by(name: 'Hiking', characteristic: ht )
MasterSkill.find_or_create_by(name: 'Hobby Skill (DX)', characteristic: dx, requires_specialization: true )
MasterSkill.find_or_create_by(name: 'Hobby Skill (IQ)', characteristic: iq, requires_specialization: true )
MasterSkill.find_or_create_by(name: 'Holdout', characteristic: iq )
MasterSkill.find_or_create_by(name: 'Innate Attack', characteristic: dx, requires_specialization: true )
MasterSkill.find_or_create_by(name: 'Interrogation', characteristic: iq )
MasterSkill.find_or_create_by(name: 'Intimidation', characteristic: will )
MasterSkill.find_or_create_by(name: 'Jeweler', characteristic: iq, requires_tech_level: true )
MasterSkill.find_or_create_by(name: 'Jitte/Sai', characteristic: dx )
MasterSkill.find_or_create_by(name: 'Judo', characteristic: dx )
MasterSkill.find_or_create_by(name: 'Jumping', characteristic: dx )
MasterSkill.find_or_create_by(name: 'Karate', characteristic: dx )
MasterSkill.find_or_create_by(name: 'Knife', characteristic: dx )
MasterSkill.find_or_create_by(name: 'Knot-Tying', characteristic: dx )
MasterSkill.find_or_create_by(name: 'Kusari', characteristic: dx )
MasterSkill.find_or_create_by(name: 'Lance', characteristic: dx )
MasterSkill.find_or_create_by(name: 'Lasso', characteristic: dx )
MasterSkill.find_or_create_by(name: 'Leadership', characteristic: iq )
MasterSkill.find_or_create_by(name: 'Leatherworking', characteristic: dx )
MasterSkill.find_or_create_by(name: 'Lifting', characteristic: ht )
MasterSkill.find_or_create_by(name: 'Lip Reading', characteristic: per )
MasterSkill.find_or_create_by(name: 'Lockpicking', characteristic: iq, requires_tech_level: true )
MasterSkill.find_or_create_by(name: 'Main-Gauche', characteristic: dx )
MasterSkill.find_or_create_by(name: 'Meditation', characteristic: will )
MasterSkill.find_or_create_by(name: 'Merchant', characteristic: iq )
MasterSkill.find_or_create_by(name: 'Mimicry', characteristic: iq, requires_specialization: true )
MasterSkill.find_or_create_by(name: 'Musical Composition', characteristic: iq )
MasterSkill.find_or_create_by(name: 'Musical Instrument', characteristic: iq, requires_specialization: true )
MasterSkill.find_or_create_by(name: 'Naturalist', characteristic: iq )
MasterSkill.find_or_create_by(name: 'Navigation', characteristic: iq, requires_specialization: true, requires_tech_level: true )
MasterSkill.find_or_create_by(name: 'Net', characteristic: dx )
MasterSkill.find_or_create_by(name: 'Observation', characteristic: per )
MasterSkill.find_or_create_by(name: 'Occultism', characteristic: iq )
MasterSkill.find_or_create_by(name: 'Packing', characteristic: iq )
MasterSkill.find_or_create_by(name: 'Panhandling', characteristic: iq )
MasterSkill.find_or_create_by(name: 'Performance', characteristic: iq )
MasterSkill.find_or_create_by(name: 'Pharmacy', characteristic: iq, requires_specialization: true, requires_tech_level: true )
MasterSkill.find_or_create_by(name: 'Philosophy', characteristic: iq )
MasterSkill.find_or_create_by(name: 'Physiology', characteristic: iq, requires_specialization: true, requires_tech_level: true )
MasterSkill.find_or_create_by(name: 'Pickpocket', characteristic: dx )
MasterSkill.find_or_create_by(name: 'Poetry', characteristic: iq )
MasterSkill.find_or_create_by(name: 'Poisons', characteristic: iq, requires_tech_level: true )
MasterSkill.find_or_create_by(name: 'Polearm', characteristic: dx )
MasterSkill.find_or_create_by(name: 'Professional Skill (IQ)', characteristic: iq, requires_specialization: true )
MasterSkill.find_or_create_by(name: 'Professional Skill (DX)', characteristic: dx, requires_specialization: true )
MasterSkill.find_or_create_by(name: 'Propaganda', characteristic: iq, requires_tech_level: true )
MasterSkill.find_or_create_by(name: 'Prospecting', characteristic: iq, requires_tech_level: true )
MasterSkill.find_or_create_by(name: 'Psychology', characteristic: iq )
MasterSkill.find_or_create_by(name: 'Public Speaking', characteristic: iq )
MasterSkill.find_or_create_by(name: 'Rapier', characteristic: dx )
MasterSkill.find_or_create_by(name: 'Religious Ritual', characteristic: iq, requires_specialization: true )
MasterSkill.find_or_create_by(name: 'Research', characteristic: iq, requires_tech_level: true )
MasterSkill.find_or_create_by(name: 'Riding', characteristic: dx, requires_specialization: true )
MasterSkill.find_or_create_by(name: 'Running', characteristic: ht )
MasterSkill.find_or_create_by(name: 'Saber', characteristic: dx )
MasterSkill.find_or_create_by(name: 'Savoir-Faire', characteristic: iq, requires_specialization: true )
MasterSkill.find_or_create_by(name: 'Scrounging', characteristic: per )
MasterSkill.find_or_create_by(name: 'Seamanship', characteristic: iq, requires_tech_level: true )
MasterSkill.find_or_create_by(name: 'Search', characteristic: per )
MasterSkill.find_or_create_by(name: 'Sex Appeal', characteristic: ht )
MasterSkill.find_or_create_by(name: 'Shadowing', characteristic: iq )
MasterSkill.find_or_create_by(name: 'Shield', characteristic: dx, requires_specialization: true )
MasterSkill.find_or_create_by(name: 'Shortsword', characteristic: dx )
MasterSkill.find_or_create_by(name: 'Singing', characteristic: ht )
MasterSkill.find_or_create_by(name: 'Skiing', characteristic: ht )
MasterSkill.find_or_create_by(name: 'Sleight of Hand', characteristic: dx )
MasterSkill.find_or_create_by(name: 'Sling', characteristic: dx )
MasterSkill.find_or_create_by(name: 'Smallsword', characteristic: dx )
MasterSkill.find_or_create_by(name: 'Smith', characteristic: iq, requires_specialization: true, requires_tech_level: true )
MasterSkill.find_or_create_by(name: 'Smuggling', characteristic: iq )
MasterSkill.find_or_create_by(name: 'Spear', characteristic: dx )
MasterSkill.find_or_create_by(name: 'Spear Thrower', characteristic: dx )
MasterSkill.find_or_create_by(name: 'Speed-Reading', characteristic: iq )
MasterSkill.find_or_create_by(name: 'Staff', characteristic: dx )
MasterSkill.find_or_create_by(name: 'Stealth', characteristic: dx )
MasterSkill.find_or_create_by(name: 'Strategy', characteristic: iq, requires_specialization: true )
MasterSkill.find_or_create_by(name: 'Streetwise', characteristic: iq )
MasterSkill.find_or_create_by(name: 'Sumo Wrestling', characteristic: dx )
MasterSkill.find_or_create_by(name: 'Surgery', characteristic: iq, requires_tech_level: true )
MasterSkill.find_or_create_by(name: 'Survival', characteristic: per, requires_specialization: true )
MasterSkill.find_or_create_by(name: 'Swimming', characteristic: ht )
MasterSkill.find_or_create_by(name: 'Tactics', characteristic: iq )
MasterSkill.find_or_create_by(name: 'Teaching', characteristic: iq )
MasterSkill.find_or_create_by(name: 'Teamster', characteristic: iq, requires_specialization: true )
MasterSkill.find_or_create_by(name: 'Thaumatology', characteristic: iq )
MasterSkill.find_or_create_by(name: 'Theology', characteristic: iq, requires_specialization: true )
MasterSkill.find_or_create_by(name: 'Throwing', characteristic: dx )
MasterSkill.find_or_create_by(name: 'Thrown Weapon', characteristic: dx, requires_specialization: true )
MasterSkill.find_or_create_by(name: 'Tonfa', characteristic: dx )
MasterSkill.find_or_create_by(name: 'Tracking', characteristic: per )
MasterSkill.find_or_create_by(name: 'Traps', characteristic: iq, requires_tech_level: true )
MasterSkill.find_or_create_by(name: 'Two-Handed Axe/Mace', characteristic: dx )
MasterSkill.find_or_create_by(name: 'Two-Handed Flail', characteristic: dx )
MasterSkill.find_or_create_by(name: 'Two-Handed Sword', characteristic: dx )
MasterSkill.find_or_create_by(name: 'Urban Survival', characteristic: per )
MasterSkill.find_or_create_by(name: 'Ventriloquism', characteristic: iq )
MasterSkill.find_or_create_by(name: 'Veterinary', characteristic: iq, requires_tech_level: true )
MasterSkill.find_or_create_by(name: 'Weather Sense', characteristic: iq )
MasterSkill.find_or_create_by(name: 'Whip', characteristic: dx )
MasterSkill.find_or_create_by(name: 'Wrestling', characteristic: dx )
MasterSkill.find_or_create_by(name: 'Writing', characteristic: iq )

Book.find_or_create_by(name: "Dungeon Fantasy 2: Dungeons", abbreviation: "DF2")
Book.find_or_create_by(name: "Dungeon Fantasy Monsters 1", abbreviation: "DFM1")
