# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
MoveType.create(name: 'ground')
MoveType.create(name: 'water')
MoveType.create(name: 'air')
MoveType.create(name: 'tunneling')

Location.create(name: 'eye')
Location.create(name: 'skull')
Location.create(name: 'face')
Location.create(name: 'right leg')
Location.create(name: 'right arm')
Location.create(name: 'torso')
Location.create(name: 'groin/abdomen')
Location.create(name: 'left arm')
Location.create(name: 'left leg')
Location.create(name: 'right hand')
Location.create(name: 'left hand')
Location.create(name: 'right foot')
Location.create(name: 'left foot')
Location.create(name: 'neck')
Location.create(name: 'vitals')

MonsterClass.create(name: 'Animal')
MonsterClass.create(name: 'Animal, Dire')
MonsterClass.create(name: 'Animal, Giant')
MonsterClass.create(name: 'Construct')
MonsterClass.create(name: 'Demon')
MonsterClass.create(name: 'Elder Thing')
MonsterClass.create(name: 'Elemental')
MonsterClass.create(name: 'Faerie')
MonsterClass.create(name: 'Hybrid')
MonsterClass.create(name: 'Mundane')
MonsterClass.create(name: 'Plant')
MonsterClass.create(name: 'Slime')
MonsterClass.create(name: 'Undead')


st =Characteristic.create(name: 'ST', sequence_number: 1 )
dx = Characteristic.create(name: 'DX', sequence_number: 2 )
iq = Characteristic.create(name: 'IQ', sequence_number: 3 )
ht = Characteristic.create(name: 'HT', sequence_number: 4 )
Characteristic.create(name: 'HP', sequence_number: 5 )
will = Characteristic.create(name: 'Will', sequence_number: 6 )
per = Characteristic.create(name: 'Per', sequence_number: 7 )
Characteristic.create(name: 'Fatigue', sequence_number: 8 )
Characteristic.create(name: 'SM', sequence_number: 9 )
Characteristic.create(name: 'Speed', sequence_number: 10, step_size: 0.25 )


MasterSkill.create(name: 'Acrobatics', characteristic: dx )
MasterSkill.create(name: 'Acting', characteristic: iq )
MasterSkill.create(name: 'Alchemy/TL3', characteristic: iq )
MasterSkill.create(name: 'Animal Handling (Big Cats)', characteristic: iq )
MasterSkill.create(name: 'Animal Handling (Dogs)', characteristic: iq )
MasterSkill.create(name: 'Animal Handling (Equines)', characteristic: iq )
MasterSkill.create(name: 'Animal Handling (Raptors)', characteristic: iq )
MasterSkill.create(name: 'Architecture/TL3', characteristic: iq )
MasterSkill.create(name: 'Area Knowledge (Tembladera)', characteristic: iq )
MasterSkill.create(name: 'Armoury (Body Armor)', characteristic: iq )
MasterSkill.create(name: 'Armoury (Melee Weapons)', characteristic: iq )
MasterSkill.create(name: 'Armoury (Missile Weapons)', characteristic: iq )
MasterSkill.create(name: 'Axe/Mace', characteristic: dx )
MasterSkill.create(name: 'Blowpipe', characteristic: dx )
MasterSkill.create(name: 'Boating (Large Powerboat)', characteristic: dx )
MasterSkill.create(name: 'Boating (Motorboat)', characteristic: dx )
MasterSkill.create(name: 'Boating (Sailboat)', characteristic: dx )
MasterSkill.create(name: 'Boating (Unpowered)', characteristic: dx )
MasterSkill.create(name: 'Body Language', characteristic: per )
MasterSkill.create(name: 'Body Sense', characteristic: dx )
MasterSkill.create(name: 'Bolas', characteristic: dx )
MasterSkill.create(name: 'Bow', characteristic: dx )
MasterSkill.create(name: 'Boxing', characteristic: dx )
MasterSkill.create(name: 'Brawling', characteristic: dx )
MasterSkill.create(name: 'Broadsword', characteristic: dx )
MasterSkill.create(name: 'Camouflage', characteristic: iq )
MasterSkill.create(name: 'Carousing', characteristic: ht )
MasterSkill.create(name: 'Cartography', characteristic: iq )
MasterSkill.create(name: 'Climbing', characteristic: dx )
MasterSkill.create(name: 'Cloak', characteristic: dx )
MasterSkill.create(name: 'Counterfeiting/TL3', characteristic: iq )
MasterSkill.create(name: 'Crossbow', characteristic: dx )
MasterSkill.create(name: 'Current Affairs (High Culture)', characteristic: iq )
MasterSkill.create(name: 'Current Affairs (Popular Culture)', characteristic: iq )
MasterSkill.create(name: 'Dancing', characteristic: dx )
MasterSkill.create(name: 'Detect Lies', characteristic: per )
MasterSkill.create(name: 'Diagnosis/TL3', characteristic: iq )
MasterSkill.create(name: 'Diplomacy', characteristic: iq )
MasterSkill.create(name: 'Disguise/TL3', characteristic: iq )
MasterSkill.create(name: 'Engineer (Body Armor)/TL3', characteristic: iq )
MasterSkill.create(name: 'Engineer (Clockwork)/TL3', characteristic: iq )
MasterSkill.create(name: 'Engineer (Glider)/TL3', characteristic: iq )
MasterSkill.create(name: 'Engineer (Lighter-Than-Air)/TL3', characteristic: iq )
MasterSkill.create(name: 'Engineer (Melee Weapons)/TL3', characteristic: iq )
MasterSkill.create(name: 'Engineer (Missile Weapons)/TL3', characteristic: iq )
MasterSkill.create(name: 'Engineer (Rockets)/TL3', characteristic: iq )
MasterSkill.create(name: 'Engineer (Sailboat)/TL3', characteristic: iq )
MasterSkill.create(name: 'Engineer (Steam Engine)/TL3', characteristic: iq )
MasterSkill.create(name: 'Engineer (Unpowered Boat)/TL3', characteristic: iq )
MasterSkill.create(name: 'Engineer (Artillery)/TL3', characteristic: iq )
MasterSkill.create(name: 'Engineer (Civil)/TL3', characteristic: iq )
MasterSkill.create(name: 'Engineer (Combat)/TL3', characteristic: iq )
MasterSkill.create(name: 'Engineer (Mining)/TL3', characteristic: iq )
MasterSkill.create(name: 'Erotic Art', characteristic: dx )
MasterSkill.create(name: 'Escape', characteristic: dx )
MasterSkill.create(name: 'Falconry', characteristic: iq )
MasterSkill.create(name: 'Fast-Draw (Knife)', characteristic: dx )
MasterSkill.create(name: 'Fast-Draw (Sword)', characteristic: dx )
MasterSkill.create(name: 'Fast-Draw (Two-Handed Sword)', characteristic: dx )
MasterSkill.create(name: 'Fast-Draw (Arrow)', characteristic: dx )
MasterSkill.create(name: 'Fast-Draw (Shuriken)', characteristic: dx )
MasterSkill.create(name: 'Fast-Draw (Dart)', characteristic: dx )
MasterSkill.create(name: 'Fast-Talk', characteristic: iq )
MasterSkill.create(name: 'Filch', characteristic: dx )
MasterSkill.create(name: 'First Aid/TL3', characteristic: iq )
MasterSkill.create(name: 'Fishing', characteristic: per )
MasterSkill.create(name: 'Flail', characteristic: dx )
MasterSkill.create(name: 'Forced Entry', characteristic: dx )
MasterSkill.create(name: 'Forgery/TL3', characteristic: iq )
MasterSkill.create(name: 'Gambling', characteristic: iq )
MasterSkill.create(name: 'Games (Chess)', characteristic: iq )
MasterSkill.create(name: 'Games (Go)', characteristic: iq )
MasterSkill.create(name: 'Garrote', characteristic: dx )
MasterSkill.create(name: 'Gesture', characteristic: iq )
MasterSkill.create(name: 'Hazardous Materials (Magical)', characteristic: iq )
MasterSkill.create(name: 'Heraldry', characteristic: iq )
MasterSkill.create(name: 'Hidden Lore (Demons)', characteristic: iq )
MasterSkill.create(name: 'Hidden Lore (Elder Things)', characteristic: iq )
MasterSkill.create(name: 'Hidden Lore (Magic Items)', characteristic: iq )
MasterSkill.create(name: 'Hidden Lore (Magical Writings)', characteristic: iq )
MasterSkill.create(name: 'Hidden Lore (Dragons)', characteristic: iq )
MasterSkill.create(name: 'Hidden Lore (Elementals)', characteristic: iq )
MasterSkill.create(name: 'Hidden Lore (Faerie Lore)', characteristic: iq )
MasterSkill.create(name: 'Hidden Lore (Hidden Styles)', characteristic: iq )
MasterSkill.create(name: 'Hidden Lore (Lost Civilizations)', characteristic: iq )
MasterSkill.create(name: 'Hidden Lore (Nature Spirits)', characteristic: iq )
MasterSkill.create(name: 'Hidden Lore (Undead)', characteristic: iq )
MasterSkill.create(name: 'Hiking', characteristic: ht )
MasterSkill.create(name: 'Hobby Skill DX/E or', characteristic: iq )
MasterSkill.create(name: 'Holdout', characteristic: iq )
MasterSkill.create(name: 'Innate Attack (Beam)', characteristic: dx )
MasterSkill.create(name: 'Innate Attack (Breath)', characteristic: dx )
MasterSkill.create(name: 'Innate Attack (Gaze)', characteristic: dx )
MasterSkill.create(name: 'Innate Attack (Projectile)', characteristic: dx )
MasterSkill.create(name: 'Interrogation', characteristic: iq )
MasterSkill.create(name: 'Intimidation', characteristic: will )
MasterSkill.create(name: 'Jeweler/TL3', characteristic: iq )
MasterSkill.create(name: 'Jitte/Sai', characteristic: dx )
MasterSkill.create(name: 'Judo', characteristic: dx )
MasterSkill.create(name: 'Jumping', characteristic: dx )
MasterSkill.create(name: 'Karate', characteristic: dx )
MasterSkill.create(name: 'Knife', characteristic: dx )
MasterSkill.create(name: 'Knot-Tying', characteristic: dx )
MasterSkill.create(name: 'Kusari', characteristic: dx )
MasterSkill.create(name: 'Lance', characteristic: dx )
MasterSkill.create(name: 'Lasso', characteristic: dx )
MasterSkill.create(name: 'Leadership', characteristic: iq )
MasterSkill.create(name: 'Leatherworking', characteristic: dx )
MasterSkill.create(name: 'Lifting', characteristic: ht )
MasterSkill.create(name: 'Lip Reading', characteristic: per )
MasterSkill.create(name: 'Lockpicking/TL3', characteristic: iq )
MasterSkill.create(name: 'Main-Gauche', characteristic: dx )
MasterSkill.create(name: 'Meditation', characteristic: will )
MasterSkill.create(name: 'Merchant', characteristic: iq )
MasterSkill.create(name: 'Mimicry (Animal Sounds)', characteristic: iq )
MasterSkill.create(name: 'Mimicry (Bird Calls)', characteristic: iq )
MasterSkill.create(name: 'Mimicry (Speech)', characteristic: iq )
MasterSkill.create(name: 'Musical Composition', characteristic: iq )
MasterSkill.create(name: 'Musical Instrument (Stringed)', characteristic: iq )
MasterSkill.create(name: 'Musical Instrument (Harp)', characteristic: iq )
MasterSkill.create(name: 'Musical Instrument (Harmonica)', characteristic: iq )
MasterSkill.create(name: 'Naturalist', characteristic: iq )
MasterSkill.create(name: 'Navigation (Land)/TL3', characteristic: iq )
MasterSkill.create(name: 'Navigation (Sea)/TL3', characteristic: iq )
MasterSkill.create(name: 'Navigation (Air)/TL3', characteristic: iq )
MasterSkill.create(name: 'Net', characteristic: dx )
MasterSkill.create(name: 'Observation', characteristic: per )
MasterSkill.create(name: 'Occultism', characteristic: iq )
MasterSkill.create(name: 'Packing', characteristic: iq )
MasterSkill.create(name: 'Panhandling', characteristic: iq )
MasterSkill.create(name: 'Performance', characteristic: iq )
MasterSkill.create(name: 'Pharmacy/TL3 (Herbal)', characteristic: iq )
MasterSkill.create(name: 'Philosophy', characteristic: iq )
MasterSkill.create(name: 'Physiology (Elder Thing)/TL3', characteristic: iq )
MasterSkill.create(name: 'Physiology (Human)/TL3', characteristic: iq )
MasterSkill.create(name: 'Pickpocket', characteristic: dx )
MasterSkill.create(name: 'Poetry', characteristic: iq )
MasterSkill.create(name: 'Poisons/TL3', characteristic: iq )
MasterSkill.create(name: 'Polearm', characteristic: dx )
MasterSkill.create(name: 'Professional Skill DX/A or', characteristic: iq )
MasterSkill.create(name: 'Propaganda/TL3', characteristic: iq )
MasterSkill.create(name: 'Prospecting/TL3', characteristic: iq )
MasterSkill.create(name: 'Psychology', characteristic: iq )
MasterSkill.create(name: 'Public Speaking', characteristic: iq )
MasterSkill.create(name: 'Rapier', characteristic: dx )
MasterSkill.create(name: 'Religious Ritual (Good Church)', characteristic: iq )
MasterSkill.create(name: 'Religious Ritual (Demon Worship)', characteristic: iq )
MasterSkill.create(name: 'Research/TL3', characteristic: iq )
MasterSkill.create(name: 'Riding (Equine)', characteristic: dx )
MasterSkill.create(name: 'Running', characteristic: ht )
MasterSkill.create(name: 'Saber', characteristic: dx )
MasterSkill.create(name: 'Savoir-Faire (High Society)', characteristic: iq )
MasterSkill.create(name: 'Scrounging', characteristic: per )
MasterSkill.create(name: 'Seamanship/TL3', characteristic: iq )
MasterSkill.create(name: 'Search', characteristic: per )
MasterSkill.create(name: 'Sex Appeal', characteristic: ht )
MasterSkill.create(name: 'Shadowing', characteristic: iq )
MasterSkill.create(name: 'Shield (Buckler)', characteristic: dx )
MasterSkill.create(name: 'Shield (Shield)', characteristic: dx )
MasterSkill.create(name: 'Shortsword', characteristic: dx )
MasterSkill.create(name: 'Singing', characteristic: ht )
MasterSkill.create(name: 'Skiing', characteristic: ht )
MasterSkill.create(name: 'Sleight of Hand', characteristic: dx )
MasterSkill.create(name: 'Sling', characteristic: dx )
MasterSkill.create(name: 'Smallsword', characteristic: dx )
MasterSkill.create(name: 'Smith (Copper)/TL3', characteristic: iq )
MasterSkill.create(name: 'Smith (Iron)/TL3', characteristic: iq )
MasterSkill.create(name: 'Smith (Tin and Lead)/TL3', characteristic: iq )
MasterSkill.create(name: 'Smuggling', characteristic: iq )
MasterSkill.create(name: 'Spear', characteristic: dx )
MasterSkill.create(name: 'Spear Thrower', characteristic: dx )
MasterSkill.create(name: 'Speed-Reading', characteristic: iq )
MasterSkill.create(name: 'Staff', characteristic: dx )
MasterSkill.create(name: 'Stealth', characteristic: dx )
MasterSkill.create(name: 'Strategy (Land)', characteristic: iq )
MasterSkill.create(name: 'Strategy (Naval)', characteristic: iq )
MasterSkill.create(name: 'Streetwise', characteristic: iq )
MasterSkill.create(name: 'Sumo Wrestling', characteristic: dx )
MasterSkill.create(name: 'Surgery/TL3', characteristic: iq )
MasterSkill.create(name: 'Survival (Arctic)', characteristic: per )
MasterSkill.create(name: 'Survival (Desert)', characteristic: per )
MasterSkill.create(name: 'Survival (Dungeon)', characteristic: per )
MasterSkill.create(name: 'Survival (Island/Beach)', characteristic: per )
MasterSkill.create(name: 'Survival (Jungle)', characteristic: per )
MasterSkill.create(name: 'Survival (Mountain)', characteristic: per )
MasterSkill.create(name: 'Survival (Plains)', characteristic: per )
MasterSkill.create(name: 'Survival (Subterranean)', characteristic: per )
MasterSkill.create(name: 'Survival (Swampland)', characteristic: per )
MasterSkill.create(name: 'Survival (Woodlands)', characteristic: per )
MasterSkill.create(name: 'Swimming', characteristic: ht )
MasterSkill.create(name: 'Tactics', characteristic: iq )
MasterSkill.create(name: 'Teaching', characteristic: iq )
MasterSkill.create(name: 'Teamster (Equine)', characteristic: iq )
MasterSkill.create(name: 'Teamster (Cave Goat)', characteristic: iq )
MasterSkill.create(name: 'Thaumatology', characteristic: iq )
MasterSkill.create(name: 'Theology (Good Church)', characteristic: iq )
MasterSkill.create(name: 'Theology (Demon Worship)', characteristic: iq )
MasterSkill.create(name: 'Throwing', characteristic: dx )
MasterSkill.create(name: 'Thrown Weapon (Axe/Mace)', characteristic: dx )
MasterSkill.create(name: 'Thrown Weapon (Dart)', characteristic: dx )
MasterSkill.create(name: 'Thrown Weapon (Disc)', characteristic: dx )
MasterSkill.create(name: 'Thrown Weapon (Harpoon)', characteristic: dx )
MasterSkill.create(name: 'Thrown Weapon (Knife)', characteristic: dx )
MasterSkill.create(name: 'Thrown Weapon (Shuriken)', characteristic: dx )
MasterSkill.create(name: 'Thrown Weapon (Spear)', characteristic: dx )
MasterSkill.create(name: 'Thrown Weapon (Stick)', characteristic: dx )
MasterSkill.create(name: 'Tonfa', characteristic: dx )
MasterSkill.create(name: 'Tracking', characteristic: per )
MasterSkill.create(name: 'Traps/TL3', characteristic: iq )
MasterSkill.create(name: 'Two-Handed Axe/Mace', characteristic: dx )
MasterSkill.create(name: 'Two-Handed Flail', characteristic: dx )
MasterSkill.create(name: 'Two-Handed Sword', characteristic: dx )
MasterSkill.create(name: 'Urban Survival', characteristic: per )
MasterSkill.create(name: 'Ventriloquism', characteristic: iq )
MasterSkill.create(name: 'Veterinary/TL3', characteristic: iq )
MasterSkill.create(name: 'Weather Sense', characteristic: iq )
MasterSkill.create(name: 'Whip', characteristic: dx )
MasterSkill.create(name: 'Wrestling', characteristic: dx )
MasterSkill.create(name: 'Writing', characteristic: iq )
